### ISSUE TITLE
icon for AND Player

### ISSUE THREAD

**Issue by hafizahmmed** [yaostyle/AND-Player#1]
Hello,
Good Day, i make a logo icon for your project.Because there is no logo in your project. If you want to use this icon in your project, then comment below, I will give you the source file. And if you want a change, then tell me I will change.

![andplayer-01](https://user-images.githubusercontent.com/38810169/40015975-bdadd25e-57d6-11e8-9c6a-62679a28e11e.jpg)

**Comment by yaostyle** [comment]
Thanks @hafizahmmed but I will work on an icon for it. Good icon, though.

**Comment by hafizahmmed** [comment]
when you add license??

**Comment by hafizahmmed** [comment]
If you want to apply this icon to your project, then I will give you the source file

**Comment by yaostyle** [comment]
@hafizahmmed Thanks I meant I'll work on my own icons later.
